from pathlib import Path

import pandas as pd

# render it with jinja
from jinja2 import Template
from rdagent.factor_implementation.share_modules.factor_implementation_config import FACTOR_IMPLEMENT_SETTINGS

TPL = """
{{file_name}}
```{{type_desc}}
{{content}}
````
"""
# Create a Jinja template from the string
JJ_TPL = Template(TPL)


def get_data_folder_intro() -> str:
    """Directly get the info of the data folder.
    It is for preparing prompting message.
    """
    content_list = []
    for p in Path(FACTOR_IMPLEMENT_SETTINGS.file_based_execution_data_folder).iterdir():
        if p.name.endswith(".h5"):
            data_frame = pd.read_hdf(p)
            # get data_frame.head() as string with full width
            pd.set_option("display.max_columns", None)  # or 1000
            pd.set_option("display.max_rows", None)  # or 1000
            pd.set_option("display.max_colwidth", None)  # or 199
            rendered = JJ_TPL.render(
                file_name=p.name,
                type_desc="generated by `pd.read_hdf(filename).head()`",
                content=data_frame.head().to_string(),
            )
            content_list.append(rendered)
        elif p.name.endswith(".md"):
            with p.open() as f:
                content = f.read()
                rendered = JJ_TPL.render(
                    file_name=p.name,
                    type_desc="markdown",
                    content=content,
                )
                content_list.append(rendered)
        else:
            error_message = f"file type {p.name} is not supported. Please implement its description function."
            raise NotImplementedError(error_message)
    return "\n ----------------- file spliter -------------\n".join(content_list)
