# 1. Pull down your Azure Container Registry image
FROM rdagentappregistry.azurecr.io/rd-agent-mle:20250623

# 2. (Optional) install any additional tools you need
#    e.g. git, bash-completion, etc.
# RUN apt update && \
#     apt install -y git bash-completion && \
#     rm -rf /var/lib/apt/lists/*
RUN apt update && \
    apt install -y git bash-completion
