name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  release_and_publish:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Release please
        id: release_please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        if: ${{ steps.release_please.outputs.release_created }}
        with:
          fetch-depth: 0
      - name: Set up Python
        if: ${{ steps.release_please.outputs.release_created }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          cache: pip
          python-version: '3.10'
      - name: Install dependencies
        if: ${{ steps.release_please.outputs.release_created }}
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine  #  better-exceptions(optional for debug)
      - run: make dev
        if: ${{ steps.release_please.outputs.release_created }}
      - run: make build
        if: ${{ steps.release_please.outputs.release_created }}
      - name: upload
        if: ${{ steps.release_please.outputs.release_created }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          make upload
