/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartBox: typeof import('./src/components/chartBox.vue')['default']
    Code: typeof import('./src/components/code.vue')['default']
    Development: typeof import('./src/components/development.vue')['default']
    Dialog: typeof import('./src/components/dialog.vue')['default']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Feedback: typeof import('./src/components/feedback.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    KateX: typeof import('./src/components/kateX.vue')['default']
    LineChart: typeof import('./src/components/lineChart.vue')['default']
    LineChartOne: typeof import('./src/components/lineChartOne.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    LoadingDot: typeof import('./src/components/loading-dot.vue')['default']
    LoopComponent: typeof import('./src/components/loop-component.vue')['default']
    Markdown: typeof import('./src/components/markdown.vue')['default']
    MarkdownToHtml: typeof import('./src/components/markdownToHtml.vue')['default']
    NavBar: typeof import('./src/components/navBar.vue')['default']
    Research: typeof import('./src/components/research.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveImage: typeof import('./src/components/saveImage.vue')['default']
    SelectComponent: typeof import('./src/components/select-component.vue')['default']
    SmSelectComponent: typeof import('./src/components/sm-select-component.vue')['default']
    StepComponent: typeof import('./src/components/step-component.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon.vue')['default']
    Swiper: typeof import('./src/components/swiper.vue')['default']
    UploadProgress: typeof import('./src/components/upload-progress.vue')['default']
  }
}
